Exams/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('exams_list/', ListExams.as_view(), name='ListExams'),
    path('exam_create/', CreateExam.as_view(), name='CreateExam'),
    path('subject_create/', SubjectCreate.as_view(), name='SubjectCreate'),
    path('exam_detail/<pk>', ExamDetail.as_view(), name='ExamDetail'),
    path('exam_delete/<pk>', ExamDelete.as_view(), name='ExamDelete'),
    path('exam_update/<pk>', ExamUpdate.as_view(), name='ExamUpdate'),
    path('question_create/<int:exam_id>', QuestionCreate.as_view(), name='QuestionCreate'),
    path('question_delete/<pk>/<int:exam_id>', QuestionDelete.as_view(), name='QuestionDelete'),
    path('question_update/<pk>/<int:exam_id>', QuestionUpdate.as_view(), name='QuestionUpdate'),
    path('question_detail/<pk>', QuestionDetail.as_view(), name='QuestionDetail'),
    path('answer_create/<int:question_id>', AnswerCreate.as_view(), name='AnswerCreate'),
    path('answer_update/<pk>/<int:question_id>', AnswerUpdate.as_view(), name='AnswerUpdate'),
    path('answer_delete/<pk>/<int:question_id>', AnswerDelete.as_view(), name='AnswerDelete'),
    path('exam_start/<int:exam_id>', ExamAttempt.as_view(), name='ExamStart'),
    path('subject_list/', SubjectList.as_view(), name='SubjectList'),
    path('subject_update/<pk>', SubjectUpdate.as_view(), name='SubjectUpdate'),
    path('subject_delete/<pk>', SubjectDelete.as_view(), name='SubjectDelete'),
    path('exams_stats/', ExamListStats.as_view(), name='ExamStats'),
    path('exams_stats/<int:user_id>', UserExamStats.as_view(), name='UserStats'),
    path('exam_group_stats/<int:study_group>', StudyGroupStats.as_view(), name='GroupStats'),
    path('group_stats_by_exam/<int:study_group>/<int:exam_id>/', StudyGroupStatsByExam.as_view(),
         name='GroupStatsByExam'),
]

News/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('news_create/', NewsCreate.as_view(), name='CreateNews'),
    path('category_create', CategoryCreate.as_view(), name='CreateCategory'),
    path('news_remove/<pk>', RemoveNews.as_view(), name='RemoveNews'),
    path('news_update/<pk>', UpdateNews.as_view(), name='UpdateNews'),
    path('', ListNews.as_view(), name='ListNews'),
]

RExam/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import RedirectView

from RExam import settings
from .views import AboutPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('news/', include('News.urls')),
    path('', RedirectView.as_view(permanent=False, url='news/'), name='HomePage'),
    path('about/', AboutPage.as_view(), name='AboutPage'),
    path('exams/', include('Exams.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Exams/models.py
import re

from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator
from django.db.models import Model, CharField, TextField, DateField, ForeignKey, SET_NULL, CASCADE, ImageField, \
    BooleanField, IntegerField, DateTimeField, Max
from django.http import Http404
from django.urls import reverse


class Subject(Model):
    name = CharField(max_length=30, blank=False, null=False, verbose_name=u'Имя предмета')

    def __str__(self):
        return self.name

    def get_delete_url(self):
        return reverse('SubjectDelete', kwargs={'pk': self.id})

    def get_update_url(self):
        return reverse('SubjectUpdate', kwargs={'pk': self.id})

    class Meta:
        verbose_name = u'Предмет'
        verbose_name_plural = u'Предметы'


class Exam(Model):
    exam_header = CharField(max_length=30, blank=False, null=False, verbose_name=u'Заголовок экзамена')
    exam_description = TextField(blank=False, null=True, verbose_name=u'Описание экзамена')
    exam_date = DateField(auto_now_add=True, blank=False, null=True, verbose_name=u'Дата создания')
    exam_subject = ForeignKey(Subject, blank=False, null=True, on_delete=SET_NULL, verbose_name=u'Предмет')
    exam_author = ForeignKey('Accounts.UserAccount', blank=False, null=True, on_delete=SET_NULL, verbose_name=u'Автор')
    exam_time = IntegerField(blank=False, null=True, verbose_name=u'Время прохождения',
                             validators=[MinValueValidator(1, 'Время должно быть больше или равно 1-ой минуте')])

    def __str__(self):
        return self.exam_header

    def get_detail_url(self):
        return reverse('ExamDetail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('ExamDelete', kwargs={'pk': self.id})

    def get_update_url(self):
        return reverse('ExamUpdate', kwargs={'pk': self.id})

    def get_add_question_url(self):
        return reverse('QuestionCreate', kwargs={'exam_id': self.id})

    def get_start_url(self):
        return reverse('ExamStart', kwargs={'exam_id': self.id})

    def get_question_set(self):
        if Question.objects.filter(question_exam=self.pk).exists():
            return Question.objects.filter(question_exam=self.pk)
        else:
            raise Http404("Вопросы по экзамену %s отсутствут" % self.exam_header)

    def get_max_score(self):
        score = 0
        for question in self.get_question_set():
            score += question.get_max_score()
        return score

    def get_user_max_score(self, user):
        score = ExamResult.objects.filter(user=user, exam=self).aggregate(Max('score'))['score__max']
        return score

    def verify_exam(self, form, user):
        score = 0
        for form_question in form.cleaned_data:
            # get question by html id question_(id)
            question = Question.objects.get(pk=re.findall('(\d+)', form_question)[0])
            stats = question.get_stat_model()
            # get truth answers for question
            question_truth_answers_id = question.get_truth_answers_id()
            question_score = 0
            # value = id answer
            if len(form.cleaned_data[form_question]) > len(question_truth_answers_id) or len(form.cleaned_data[form_question]) == 0:
                question_score = 0
            else:
                for value in form.cleaned_data[form_question]:
                    question_score = question_score + 1 if (int(value) in question_truth_answers_id) else question_score - 1

            score += question_score if question_score >= 0 else 0
            if score < question.get_max_score():
                stats.error_score += 1
                stats.save(force_update=True)
        exam_result = ExamResult(exam=self, score=score, user=user)
        exam_result.save(force_insert=True)
        return score

    class Meta:
        verbose_name = u'Экзамен'
        verbose_name_plural = u'Экзамены'


class Question(Model):
    question_text = TextField(blank=False, null=False, verbose_name=u'Текст вопроса')
    question_exam = ForeignKey(Exam, blank=False, null=False, on_delete=CASCADE, verbose_name=u'Вопрос к экзамену')
    question_image = ImageField(upload_to='question_images', blank=True, null=True, verbose_name=u'Изображение вопроса')

    def __str__(self):
        return self.question_text

    def get_detail_url(self):
        return reverse('QuestionDetail', kwargs={'pk': self.id})

    def get_add_answer_url(self):
        return reverse('AnswerCreate', kwargs={'question_id': self.id})

    def get_delete_url(self):
        return reverse('QuestionDelete', kwargs={'pk': self.id, 'exam_id': self.question_exam.id})

    def get_update_url(self):
        return reverse('QuestionUpdate', kwargs={'pk': self.id, 'exam_id': self.question_exam.id})

    def get_answers_set(self):
        if Answer.objects.filter(answer_question=self.id).exists():
            return Answer.objects.filter(answer_question=self.id)
        else:
            raise Http404("Ответы по вопросу %s отсутствуют" % self.question_text)

    def get_truth_answers_id(self):
        if self.get_answers_set().filter(answer_truth=True).exists():
            answers = self.get_answers_set().filter(answer_truth=True)
            answers_id = []
            for answer in answers:
                answers_id.append(answer.pk)
            return answers_id
        else:
            raise Http404("Ошибка обработки правильных ответов")

    def get_max_score(self):
        return len(self.get_truth_answers_id())

    def get_stat_model(self):
        try:
            stats = QuestionStats.objects.get(question=self)
        except ObjectDoesNotExist:
            QuestionStats.objects.create(question=self, error_score=0)
            stats = QuestionStats.objects.get(question=self)
        return stats

    def get_error_score(self):
        return self.get_stat_model().error_score

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'
        db_table = 'exam_questions'


class Answer(Model):
    answer_text = TextField(blank=False, null=False, verbose_name=u'Текст ответа')
    answer_question = ForeignKey(Question, blank=False, null=False, on_delete=CASCADE, verbose_name=u'Ответ к вопросу')
    answer_image = ImageField(upload_to='answer_images', blank=True, null=True, verbose_name=u'Изображение ответа')
    answer_truth = BooleanField(blank=False, null=False, verbose_name=u'Правильный ответ?')

    def get_delete_url(self):
        return reverse('AnswerDelete', kwargs={'pk': self.id, 'question_id': self.answer_question.id})

    def get_update_url(self):
        return reverse('AnswerUpdate', kwargs={'pk': self.id, 'question_id': self.answer_question.id})

    def __str__(self):
        return self.answer_text

    class Meta:
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'
        db_table = 'exam_answers'


class ExamResult(Model):
    exam = ForeignKey(Exam, blank=False, null=False, on_delete=CASCADE, verbose_name=u'Экзамен')
    score = IntegerField(verbose_name=u'Кол-во правильных овтетов')
    user = ForeignKey('Accounts.UserAccount', blank=False, null=False, on_delete=CASCADE, verbose_name=u'Пользователь')
    exam_date = DateTimeField(auto_now_add=True, blank=False, null=False, verbose_name=u'Дата прохождения')

    class Meta:
        verbose_name = u'Результат'
        verbose_name_plural = u'Результаты'


class QuestionStats(Model):
    error_score = IntegerField(verbose_name=u'Кол-во ошибочных ответов')
    question = ForeignKey(Question, on_delete=CASCADE, verbose_name=u'Вопрос')

Exams/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea, Select
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import safe

from Exams.models import Exam, Subject, Question, Answer


class ExamsCreateForm(ModelForm):
    class Meta:
        model = Exam
        fields = ('exam_subject', 'exam_header', 'exam_description', 'exam_time')
        widgets = {
            'exam_header': TextInput(attrs={'class': 'form-control', 'placeholder': 'Заголовок'}),
            'exam_description': Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание'}),
            'exam_subject': Select(attrs={'class': 'form-control col-5 d-inline', 'placeholder': 'Предмет'}),
            'exam_time': TextInput(attrs={'class': 'form-control', 'placeholder': 'Время в минутах'}),
        }


class SubjectCreateForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя предмета'})
        }


class QuestionCreateForm(ModelForm):
    class Meta:
        model = Question
        exclude = ['question_exam']
        widgets = {
            'question_text': Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст вопроса'}),
        }


class AnswerCreateForm(ModelForm):
    class Meta:
        model = Answer
        exclude = ['answer_question']
        widgets = {
            'answer_text': Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст ответа'}),
        }


class ExamAttemptForm(forms.Form):
    def __init__(self, *args, **kwargs):
        attempted_exam = get_object_or_404(Exam, pk=kwargs.pop('exam_id', None))
        questions = attempted_exam.get_question_set()
        super(ExamAttemptForm, self).__init__(*args, **kwargs)
        for question in questions:
            choices = []
            answers_set = question.get_answers_set()
            question_label = question.question_text
            if question.question_image:
                question_label += safe(
                    '<a target="_blank" rel="noopener noreferrer" href="' + question.question_image.url + '"><img class="d-block img-thumbnail rounded" width="500px" height="500px" src="' +
                    question.question_image.url + '"/></a>')
            for answer in answers_set:
                answer_choice = answer.answer_text
                if answer.answer_image:
                    answer_choice += '<a target="_blank" rel="noopener noreferrer" href="' + answer.answer_image.url + '"><img class="d-block img-thumbnail rounded" width="300px" height="300px" src="' + answer.answer_image.url + '"/></a>'

                choices.append((answer.pk, safe(answer_choice)))
            field = forms.MultipleChoiceField(label=question_label, required=False, choices=choices,
                                              widget=forms.CheckboxSelectMultiple) if question.get_max_score() > 1 else forms.ChoiceField(
                label=question_label, required=False, choices=choices, widget=forms.RadioSelect)
            self.fields['question_%d' % question.pk] = field

Exams/templates/Exams/Subject/ListSubject.html
{% extends 'RExam/ListTable.html' %}
{% block table_header %}
    <th style="width: 3%; text-align: center" scope="col">№</th>
    <th scope="col">Название</th>
    {% if perms.Exams %}
        <th style="width: 15%;text-align: center" scope="col">Управление</th>
    {% endif %}
{% endblock table_header %}
{% block table_body %}
    {% for subject in subjects_list %}
        <tr>
            <th scope="row" class="text-center">{{ forloop.counter }}</th>
            <td>{{ subject.name }}</td>
            <td class="text-center">
                {% if perms.Exams.change_subject %}
                    <a href="{{ subject.get_update_url }}" class="text-primary mr-2">
                        <i class="fas fa-pen"></i>
                    </a>
                {% endif %}
                {% if perms.Exams.delete_subject %}
                    <a class="text-danger" href="{{ subject.get_delete_url }}"><i
                            class="fa fa-trash" aria-hidden="true"></i></a>
                {% endif %}
            </td>
        </tr>
    {% empty %}
        <tr>
            <th scope="row" class="text-center">1</th>
            <td><p class="pl-3">Предметы отсутствуют...</p></td>
        </tr>
    {% endfor %}
{% endblock table_body %}

Exams/templates/Exams/Subject/SubjectCreate.html
{% extends 'RExam/BaseContent.html' %}
{% block control-item %}{% endblock %}
{% block head_title %} Добавить предмет {% endblock head_title %}
{% block content %}
    <div class="card bg-light shadow-sm m-1">
        <form class="p-4" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h5 class="text-center">Добавить предмет</h5>
            {% for field in form %}
                <div class="form-group">
                    <label class="d-block" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="alert alert-danger mt-2">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
                <button class="btn btn-success" type="submit">Добавить</button>
            </div>

        </form>
    </div>
{% endblock content %}

Exams/templates/Exams/Subject/SubjectDelete.html
{% extends 'RExam/RemoveBase.html' %}
{% block head_title %} Удалить "{{ object.name }}" ? {% endblock %}
{% block object_name %}{{ object.name }} {% endblock object_name %}

Exams/templates/Exams/Subject/SubjectPage.html
{% extends 'RExam/BaseContent.html' %}
{% load static %}
{% block head_title %}Предметы{% endblock head_title %}
{% block head_end %}
    <link rel="stylesheet" href="{% static 'Exams/style.css' %}"/>
{% endblock head_end %}
{% block control-item %}
    {% if perms.Exams.add_exam %}
        <a class="dropdown-item" href="{% url 'CreateExam' %}"> Добавить предмет</a>
    {% endif %}
{% endblock control-item %}
{% block content %}
    <div class="m-1">
        {% include 'Exams/Subject/ListSubject.html' with subjects_list=object_list %}
    </div>
{% endblock content %}

Exams/templates/Exams/Subject/SubjectUpdate.html
{% extends 'RExam/BaseContent.html' %}
{% block control-item %}{% endblock %}
{% block head_title %} Добавить предмет {% endblock head_title %}
{% block content %}
    <div class="card bg-light shadow-sm m-1">
        <form class="p-4" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h5 class="text-center">Редактировать предмет</h5>
            {% for field in form %}
                <div class="form-group">
                    <label class="d-block" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="alert alert-danger mt-2">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
                <button class="btn btn-success" type="submit">Сохранить</button>
            </div>

        </form>
    </div>
{% endblock content %}